name: Terraform CI

on:
  push:
    branches:
      - dev
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.github/workflows/**'
  pull_request:
    branches:
      - dev
    paths:
      - '**.tf'
      - '**.tfvars'
      - '.github/workflows/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: Week1/terraform-vpc-module
        run: terraform init

      - name: Terraform Validate
        working-directory: Week1/terraform-vpc-module
        run: terraform validate

      - name: Terraform Plan
        working-directory: Week1/terraform-vpc-module
        run: terraform plan

      - name: Setup tflint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: latest

      - name: Run tflint
        working-directory: Week1/terraform-vpc-module
        run: tflint

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working-directory: Week1/terraform-vpc-module
